### ISSUE TITLE
When the codes will be available

### ISSUE THREAD

**Issue by Harry-hash** [eyalbd2/PADA#1]
I find your approaches for domain adaptation are very interesting. I am eager to see the detailed implementation in codes.

**Comment by eyalbd2** [comment]
Hi Harry,
Thanks for your kind comment!
Since the paper is currently under a "Revise & Resubmit" procedure in TACL, we are working on some (minor) modifications for the code. Once it will be published we will definitely publish our official code (and data).
Hope this will happen soon:)

Best,
Eyal

**Comment by nadavo** [comment]
Our code was released on February 6, 2022.
Closing the issue.
